# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

task: CopyFiles@2
inputs:
  SourceFolder: "$(System.DefaultWorkingDirectory)"
  Contents: |
    **/*.yaml
    **/*.tf
  TargetFolder: "$(Build.ArtifactStagingDirectory)"
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    jobs:
      - job: $(PipelineVariable)-Firstjob
        steps:
          - bash: echo Build FirstJob - $(PipelineVariable)
      - job: Secondjob
        steps:
          - bash: echo Build SecondJob - $(PipelineVariable)
          - bash: echo $(Build.BuildNumber)
          - bash: echo $(Build.BuildId)
          - bash: echo $(Build.SourceBranchName)
          - bash: echo $(Build.SourceDirectory)
          - bash: echo $(System.DefaultWorkingDirectory)
          - bash: ls -R $(System.DefaultWorkingDirectory)
          - bash: echo $(Build.ArtifactStagingDirectory)
          - bash: java -version
          - bash: node --version
          - bash: python --version
          - bash: nvm --version
# - stage: DevDeploy
#   dependsOn: Build
#   jobs:
#     - job: DevDeploy
#       steps:
#         - bash: echo Build DevDeploy job1
#     - job: DevDeploy2
#       steps:
#         - bash: echo Build DevDeploy job2
# - stage: QADeploy
#   dependsOn: DevDeploy
#   jobs:
#     - job: QADeploy
#       steps:
#         - bash: echo Build QADeploy
# - stage: ProdDeploy
#   dependsOn:
#     - DevDeploy
#     - QADeploy
#   jobs:
#     - job: ProdDeploy
#       steps:
#         - bash: echo Build ProdDeploy
